/**
 * The boot-time route audit (docs/design/T-019.md §2.10, D2; AC-3, AC-5, §5.8).
 *
 * Registered as an `onRoute` hook, so it fires at REGISTRATION time and every
 * finding is known before `ready()` resolves. A finding aborts startup — the
 * process never listens — rather than surfacing later as a runtime hole in one
 * endpoint nobody exercised.
 *
 * The hook records; it does not throw. `buildServer` reads the table after
 * `ready()` and turns a non-empty one into `fail(...)`. See `installRouteAudit`
 * for why throwing out of `onRoute` made the guarantee depend on the syntax of
 * the plugin that registered the route.
 *
 * This is what makes AC-3 and AC-5 keep holding after T-020 adds routes under
 * `src/routes/**`, a subtree this task does not own and must not edit. The
 * guarantee is not "T-020 will remember"; it is "a server whose deal-addressed
 * route skipped the gate does not start".
 *
 * Three rules:
 *
 *  1. Any URL containing `:deal_id` whose route-level `preHandler` chain lacks
 *     `dealGate` (AC-3).
 *  2. Any URL containing `:deal_id` with no `preValidation` (AC-5) — the gate
 *     reads `:deal_id` out of the params, so an unvalidated one would reach the
 *     authorization decision.
 *  3. `DELETE` anywhere, and `PUT`/`PATCH` on a `/messages` or `/receipt` path
 *     (specs/00 "Receipt layer": append-only; specs/01 archives a closed thread
 *     rather than deleting it). `@receipt`'s `ReceiptStore` has no update or
 *     delete method to call, so such a route could not do the damage its verb
 *     promises — but a route that ADVERTISES a destructive operation on an
 *     append-only trail is itself the defect.
 */

import type { FastifyInstance, RouteOptions } from 'fastify';

import { chainHasMark } from './marks.js';

export type RouteAuditFindingKind =
  | 'deal_route_without_gate'
  | 'deal_route_without_validation'
  | 'mutation_on_append_only_path';

export interface RouteAuditFinding {
  readonly kind: RouteAuditFindingKind;
  readonly method: string;
  /** The route TEMPLATE, which is a constant — never a concrete URL. */
  readonly url: string;
}

const DEAL_PARAM = ':deal_id';
const APPEND_ONLY_SEGMENTS: readonly string[] = ['/messages', '/receipt', '/notes'];

/** Pure and total, so the rule set can be asserted directly without a server. */
export function auditRoute(route: {
  readonly method: RouteOptions['method'];
  readonly url: string;
  readonly preHandler?: unknown;
  readonly preValidation?: unknown;
}): readonly RouteAuditFinding[] {
  const findings: RouteAuditFinding[] = [];
  const methods = (Array.isArray(route.method) ? route.method : [route.method]).map((m) => String(m).toUpperCase());
  const url = route.url;

  if (url.includes(DEAL_PARAM)) {
    for (const method of methods) {
      // HEAD is auto-generated by Fastify for every GET and carries the same
      // hook chain, so it is audited identically rather than exempted.
      if (!chainHasMark(route.preHandler, 'deal-gate')) {
        findings.push({ kind: 'deal_route_without_gate', method, url });
      }
      if (!chainHasMark(route.preValidation, 'validation')) {
        findings.push({ kind: 'deal_route_without_validation', method, url });
      }
    }
  }

  for (const method of methods) {
    if (method === 'DELETE') {
      findings.push({ kind: 'mutation_on_append_only_path', method, url });
      continue;
    }
    if ((method === 'PUT' || method === 'PATCH') && APPEND_ONLY_SEGMENTS.some((segment) => url.includes(segment))) {
      findings.push({ kind: 'mutation_on_append_only_path', method, url });
    }
  }

  return findings;
}

/**
 * The finding, as an error VALUE. `buildServer` raises it AFTER `ready()` from
 * the recorded table (see `installRouteAudit`), so it always reaches the
 * caller as `fail(...)` rather than as an uncaught exception.
 */
export class RouteAuditError extends Error {
  readonly findings: readonly RouteAuditFinding[];

  constructor(findings: readonly RouteAuditFinding[]) {
    super(
      `route audit failed: ${findings
        .map((finding) => `${finding.kind} on ${finding.method} ${finding.url}`)
        .join('; ')}`,
    );
    this.name = 'RouteAuditError';
    this.findings = findings;
  }
}

const AUDIT_STORE = Symbol.for('deal-copilot.api.route-audit');

/**
 * Installs the hook. The hook RECORDS and never throws — that is the whole
 * contract, and it is a correctness requirement rather than a style choice.
 *
 * avvio invokes a plugin function with no try/catch (`avvio/lib/plugin.js`
 * `Plugin.exec`: `const maybePromiseLike = func(this.server, this.options,
 * done)`). A `FastifyPluginAsync` written as a NON-async function that returns
 * a promise — the style of this service's own `healthPlugin` and
 * `webhookPlugin`, and legal for any route plugin T-020 writes — would
 * therefore throw SYNCHRONOUSLY out of `onRoute`, escape avvio before the
 * returned promise exists, and leave the boot promise forever unsettled: the process
 * hangs or dies on an uncaught exception instead of reporting the finding.
 *
 * A boot audit whose guarantee depends on the syntax a route plugin happens to
 * use is not a guarantee. So findings accumulate on the instance and
 * `buildServer` reads `auditRouteTable(app)` after `ready()`. Registration is
 * allowed to complete — nothing LISTENS until `buildServer` returns `ok`, so
 * the offending route is never reachable — and the abort names EVERY finding
 * rather than only the first route that tripped.
 */
export function installRouteAudit(app: FastifyInstance): void {
  const store: RouteAuditFinding[] = [];
  (app as unknown as Record<symbol, unknown>)[AUDIT_STORE] = store;

  app.addHook('onRoute', (route: RouteOptions) => {
    const findings = auditRoute({
      method: route.method,
      url: route.url,
      ...(route.preHandler !== undefined && { preHandler: route.preHandler }),
      ...(route.preValidation !== undefined && { preValidation: route.preValidation }),
    });
    if (findings.length === 0) return;
    store.push(...findings);
  });
}

/** Everything the audit found on this instance. Empty on a clean boot. */
export function auditRouteTable(app: FastifyInstance): readonly RouteAuditFinding[] {
  const store = (app as unknown as Record<symbol, unknown>)[AUDIT_STORE];
  return Array.isArray(store) ? (store as readonly RouteAuditFinding[]) : [];
}
